use std::path::Path;

use super::Context;
use wiki_tool::config::AppConfig;

/// Run the init command: create project directory structure.
pub fn run(ctx: &Context, _schema: &str) -> wiki_tool::Result<()> {
    let root = &ctx.project_root;

    // Create directories
    let dirs = [
        "raw",
        "wiki/sources",
        "wiki/entities",
        "wiki/concepts",
        "wiki/syntheses",
        ".wiki-tool",
    ];

    for dir in &dirs {
        let path = root.join(dir);
        std::fs::create_dir_all(&path)?;
        if ctx.verbose {
            println!("Created: {}/", dir);
        }
    }

    // Create default config if it doesn't exist
    let config_path = root.join(".wiki-tool.toml");
    if !config_path.exists() {
        AppConfig::write_default(&config_path)?;
        if !ctx.quiet {
            println!("Created: .wiki-tool.toml");
        }
    }

    // Create index.md if it doesn't exist
    let index_path = root.join("wiki/index.md");
    if !index_path.exists() {
        std::fs::write(
            &index_path,
            "# Wiki Index\n\n*Auto-generated by wiki-tool. 0 pages total.*\n",
        )?;
    }

    // Create log.md if it doesn't exist
    let log_path = root.join("wiki/log.md");
    if !log_path.exists() {
        std::fs::write(&log_path, "# Wiki Log\n\n")?;
    }

    // Create schema files
    create_schema_files(root)?;

    if !ctx.quiet {
        if ctx.json {
            let result = serde_json::json!({
                "initialized": true,
                "directories": dirs,
            });
            println!("{}", serde_json::to_string_pretty(&result)?);
        } else {
            println!("\n✓ Wiki project initialized successfully.");
            println!("  Drop source documents into raw/ and run:");
            println!("  wiki-tool ingest raw/<file>");
        }
    }

    Ok(())
}

fn create_schema_files(root: &Path) -> wiki_tool::Result<()> {
    let claude_schema = r#"# wiki-tool — Agent Schema (Claude Code)

## Available Commands

### No-LLM Commands (use these directly)
```bash
wiki-tool search <QUERY> [--limit N] [--snippet]
wiki-tool lint [--fix] [--category <C>]
wiki-tool graph [--communities] [--related <PAGE>] [-o <PATH>]
wiki-tool cache check <SOURCE>
wiki-tool cache list
wiki-tool cache clear [SOURCE]
wiki-tool extract <FILE>
wiki-tool index [--check]
wiki-tool init
```

### Workflows

**Ingest a document:**
1. Check cache: `wiki-tool cache check raw/<file>`
2. Extract text: `wiki-tool extract raw/<file>`
3. Analyze content (you do this — entity/concept extraction)
4. Generate wiki pages (you do this — create markdown with frontmatter)
5. Write pages to wiki/ directories
6. Rebuild index: `wiki-tool index`

**Answer a question:**
1. Search: `wiki-tool search "<query>" --snippet`
2. Read top results
3. Synthesize answer with [[wikilink]] citations (you do this)

**Health check:**
1. Run: `wiki-tool lint`
2. Fix issues reported

**Build graph:**
1. Run: `wiki-tool graph --communities`
2. Review graph.json for insights
"#;

    let agents_schema = r#"# wiki-tool — Agent Schema (Codex / OpenCode)

## Quick Reference

| Command | Purpose | Needs LLM? |
|---------|---------|-------------|
| `wiki-tool search <Q>` | Search wiki pages | No |
| `wiki-tool lint` | Check wiki health | No |
| `wiki-tool graph` | Build knowledge graph | No |
| `wiki-tool cache check <F>` | Check ingest cache | No |
| `wiki-tool extract <F>` | Extract text from file | No |
| `wiki-tool index` | Rebuild index.md | No |
| `wiki-tool init` | Initialize project | No |

## Ingest Workflow (Agent-Driven)

1. `wiki-tool cache check raw/<file>` — skip if cached
2. `wiki-tool extract raw/<file>` — get plain text
3. Analyze: extract entities, concepts, contradictions
4. Generate: create wiki pages with YAML frontmatter
5. Write files to wiki/{sources,entities,concepts}/
6. `wiki-tool index` — rebuild index
"#;

    let gemini_schema = r#"# wiki-tool — Agent Schema (Gemini CLI)

## Commands (No API Key Required)

- `wiki-tool search "<query>"` — BM25 search across wiki pages
- `wiki-tool lint` — find broken links, orphans, contradictions
- `wiki-tool graph --communities` — build knowledge graph with communities
- `wiki-tool cache check raw/<file>` — check if source is already ingested
- `wiki-tool extract raw/<file>` — extract plain text from any format
- `wiki-tool index` — rebuild wiki/index.md catalog
- `wiki-tool init` — initialize a new wiki project

## Agent Workflow

You ARE the LLM. Use wiki-tool for compute-heavy operations only.
Read, analyze, and generate wiki content yourself.
"#;

    let copilot_schema = r#"# wiki-tool — Agent Schema (GitHub Copilot CLI)

## Commands

All commands work without an API key. You provide the intelligence.

```
wiki-tool search <QUERY>     # Find relevant wiki pages
wiki-tool lint [--fix]        # Check wiki quality
wiki-tool graph               # Build knowledge graph
wiki-tool cache check <FILE>  # Check ingest cache
wiki-tool extract <FILE>      # Extract text from documents
wiki-tool index               # Rebuild index.md
wiki-tool init                # Initialize wiki project
```

## Ingest Pattern

1. Check cache → 2. Extract text → 3. You analyze → 4. You generate pages → 5. Rebuild index
"#;

    write_if_missing(root, "CLAUDE.md", claude_schema)?;
    write_if_missing(root, "AGENTS.md", agents_schema)?;
    write_if_missing(root, "GEMINI.md", gemini_schema)?;
    write_if_missing(root, "COPILOT.md", copilot_schema)?;

    Ok(())
}

fn write_if_missing(root: &Path, name: &str, content: &str) -> wiki_tool::Result<()> {
    let path = root.join(name);
    if !path.exists() {
        std::fs::write(&path, content)?;
    }
    Ok(())
}
