use std::path::Path;

use crate::wiki::page::{scan_wiki_pages, PageType};

/// Generate the index.md catalog from all wiki pages.
pub fn rebuild_index(wiki_root: &Path) -> crate::Result<String> {
    let pages = scan_wiki_pages(wiki_root)?;

    let mut sources = Vec::new();
    let mut entities = Vec::new();
    let mut concepts = Vec::new();
    let mut syntheses = Vec::new();

    for page in &pages {
        let entry = format!("- [{}]({})", page.title, page.path);
        match page.page_type {
            PageType::Source => sources.push(entry),
            PageType::Entity => entities.push(entry),
            PageType::Concept => concepts.push(entry),
            PageType::Synthesis => syntheses.push(entry),
        }
    }

    let mut content = String::from("# Wiki Index\n\n");
    content.push_str(&format!(
        "*Auto-generated by wiki-tool. {} pages total.*\n\n",
        pages.len()
    ));

    if !sources.is_empty() {
        content.push_str("## Sources\n\n");
        sources.sort();
        for entry in &sources {
            content.push_str(entry);
            content.push('\n');
        }
        content.push('\n');
    }

    if !entities.is_empty() {
        content.push_str("## Entities\n\n");
        entities.sort();
        for entry in &entities {
            content.push_str(entry);
            content.push('\n');
        }
        content.push('\n');
    }

    if !concepts.is_empty() {
        content.push_str("## Concepts\n\n");
        concepts.sort();
        for entry in &concepts {
            content.push_str(entry);
            content.push('\n');
        }
        content.push('\n');
    }

    if !syntheses.is_empty() {
        content.push_str("## Syntheses\n\n");
        syntheses.sort();
        for entry in &syntheses {
            content.push_str(entry);
            content.push('\n');
        }
        content.push('\n');
    }

    Ok(content)
}

/// Write the index.md file to the wiki root.
pub fn write_index(wiki_root: &Path) -> crate::Result<()> {
    let content = rebuild_index(wiki_root)?;
    let index_path = wiki_root.join("index.md");
    std::fs::write(index_path, content)?;
    Ok(())
}

/// Check if index.md is up-to-date. Returns true if current, false if stale.
pub fn check_index(wiki_root: &Path) -> crate::Result<bool> {
    let index_path = wiki_root.join("index.md");
    let expected = rebuild_index(wiki_root)?;

    if !index_path.exists() {
        return Ok(false);
    }

    let current = std::fs::read_to_string(&index_path)?;
    Ok(current == expected)
}
